import re
import unicodedata


class TextCleaner:

    RESUME_SECTIONS = {
        "SUMMARY",
        "PROFILE",
        "OBJECTIVE",
        "SKILLS",
        "TECHNICAL SKILLS",
        "WORK EXPERIENCE",
        "EXPERIENCE",
        "PROFESSIONAL EXPERIENCE",
        "PROJECTS",
        "EDUCATION",
        "CERTIFICATIONS",
        "CERTIFICATIONS & LANGUAGES",
        "LANGUAGES",
        "ACHIEVEMENTS",
    }

    def normalize_unicode(self, text):
        """
        Normalize Unicode characters while preserving
        meaningful textual information.
        """

        return unicodedata.normalize("NFKC", text)

    def remove_artifacts(self, text):
        """
        Remove characters that are typically PDF extraction
        artifacts while preserving meaningful punctuation.
        """

        # Remove replacement character generated by bad PDF extraction
        text = text.replace("\ufffd", "")

        # Convert escaped asterisk into normal asterisk
        text = text.replace("\\*", "*")

        # Remove standalone asterisks used as formatting bullets
        text = re.sub(
            r"(?m)^\s*\*\s*",
            "",
            text
        )

        # Normalize decorative bullets
        text = re.sub(
            r"(?m)^\s*[•●▪◦■□◆◇]\s*",
            "- ",
            text
        )

        return text

    def normalize_spaces(self, text):
        """
        Normalize unnecessary spaces without destroying
        line and section structure.
        """

        # Replace tabs with spaces
        text = text.replace("\t", " ")

        # Remove trailing spaces
        text = re.sub(
            r"[ \t]+$",
            "",
            text,
            flags=re.MULTILINE
        )

        # Reduce multiple spaces inside a line
        text = re.sub(
            r"[ \t]{2,}",
            " ",
            text
        )

        # Reduce excessive blank lines
        text = re.sub(
            r"\n[ \t]*\n+",
            "\n\n",
            text
        )

        return text

    def normalize_bullets(self, text):
        """
        Convert different bullet representations
        into a consistent format.
        """

        text = re.sub(
            r"(?m)^\s*[-–—]\s*",
            "- ",
            text
        )

        return text

    def fix_line_breaks(self, text):
        """
        Fix words split across lines because of PDF formatting.
        """

        text = re.sub(
            r"(\w)-\n(\w)",
            r"\1-\2",
            text
        )

        return text

    def clean(self, text):
        """
        Perform the complete text-cleaning pipeline.
        """

        text = self.normalize_unicode(text)

        text = self.remove_artifacts(text)

        text = self.fix_line_breaks(text)

        text = self.normalize_bullets(text)

        text = self.normalize_spaces(text)

        return text.strip()

    def is_section_heading(self, line):
        """
        Determine whether a line represents a known
        resume section heading.
        """

        normalized = re.sub(r"[:\-|]+$", "", line.strip().upper()).strip()

        return normalized in self.RESUME_SECTIONS

    def detect_sections(self, text):
        """
        Divide the cleaned resume into logical sections.
        """

        lines = text.splitlines()

        sections = []

        current_section = None

        for line in lines:

            stripped = line.strip()

            # Ignore completely empty lines
            if not stripped:
                continue

            # Check whether this line is a section heading
            if self.is_section_heading(stripped):

                current_section = stripped

                sections.append({
                    "section": current_section,
                    "content": []
                })

            # Add content to the current section
            elif current_section:

                sections[-1]["content"].append(stripped)

        return sections